sudo: required
services:
    - docker

before_install:
    - docker build -t rashed-08/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rashed-08/docker-react npm run test

deploy:
    provider: heroku 
    api_key: $Heroku_Key
    app: docker-react-apps
    on:
        repo: master
